// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.Text;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using AventStack.ExtentReports;
using AventStack.ExtentReports.Reporter;
using System.Threading.Tasks;


[TestFixture]
public class GIthubtestcodeTest


{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    public object SmtpConnectType { get; private set; }

    private IJavaScriptExecutor js;
    ExtentReports extent = null;

    [OneTimeSetUp]
    public void ExtentStart()
    {
        extent =  new ExtentReports();
    var htmlReporter = new ExtentHtmlReporter(@"C:\Users\Admin\source\repos\CSharpNUnitTesting\CSharpNUnitTesting\ExtentReports\TestingResults.html");
    extent.AttachReporter(htmlReporter);
    }
    [OneTimeTearDown]
    public void ExtentClose()
    {
        extent.Flush();
    }
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    public static string DecodedPassword(string password)
    {
        var encodepasswordinbytes = Convert.FromBase64String(password);
        string decodepassword = Encoding.UTF8.GetString(encodepasswordinbytes);
        return decodepassword;
    }
    [Test, Order(0), Category("OrderSkipAttribute")]

    public void gIthubtestcode()
    {
        ExtentTest test = null;
        try
        {
            test = extent.CreateTest("gIthubtestcode");
            test.Log(Status.Pass, "Chrome Browser Launched");
            driver.Navigate().GoToUrl("https://github.com/");
            driver.Manage().Window.Maximize();
            test.Log(Status.Pass, "github URL Enterd");
            string password = DecodedPassword("Q29yYnlwb3ByODAw");
            {
                var element = driver.FindElement(By.CssSelector(".d-lg-flex:nth-child(3)"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).ClickAndHold().Perform();
            }
            {
                var element = driver.FindElement(By.CssSelector(".d-lg-flex:nth-child(3)"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.CssSelector(".d-lg-flex:nth-child(3)"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Release().Perform();
            }
            driver.FindElement(By.CssSelector(".d-lg-flex:nth-child(3)")).Click();
            driver.FindElement(By.LinkText("Sign in")).Click();
            Thread.Sleep(1000);
            driver.FindElement(By.Id("login_field")).SendKeys("rockzshiva@gmail.com");
            Thread.Sleep(1000);
            test.Log(Status.Pass, "Email ID Enterd");
            driver.FindElement(By.Id("password")).SendKeys(password);
            Thread.Sleep(1000);
            driver.FindElement(By.Id("password")).SendKeys(Keys.Enter);
            Thread.Sleep(1000);
            test.Log(Status.Pass, "Password Enterd");
            {
                var element = driver.FindElement(By.CssSelector("#dashboard-repos-container > #repos-container .css-truncate:nth-child(3)"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
                test.Log(Status.Pass, "This is Main Dasboard");
                Thread.Sleep(3000);
            }
            //Thread.Sleep(2000);
            driver.FindElement(By.CssSelector("#dashboard-repos-container > #repos-container .css-truncate:nth-child(3)")).Click();
            driver.FindElement(By.LinkText("first")).Click();
            Thread.Sleep(1000);
            test.Log(Status.Pass, "First folder clicked");
            Thread.Sleep(2000);

            {
                var element = driver.FindElement(By.LinkText(". ."));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
                Thread.Sleep(1000);
            }
            {
                var element = driver.FindElement(By.LinkText(". ."));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
                Thread.Sleep(1000);
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
                Thread.Sleep(2000);
            }
            driver.FindElement(By.LinkText("first.txt")).Click();
            Thread.Sleep(2000);
            test.Log(Status.Pass, "First.txt file opened");

            driver.FindElement(By.CssSelector(".logged-in")).Click();
            Thread.Sleep(2000);
            driver.FindElement(By.CssSelector(".logged-in")).Click();
            Thread.Sleep(2000);
            {
                var element = driver.FindElement(By.LinkText("All the files were moved to three other folders"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
                Thread.Sleep(500);
            }
            driver.FindElement(By.CssSelector(".selected > span:nth-child(2)")).Click();
            Thread.Sleep(1000);
            {
                var element = driver.FindElement(By.CssSelector(".selected > span:nth-child(2)"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
                Thread.Sleep(1000);
            }
            {
                Thread.Sleep(1000);
                var element = driver.FindElement(By.LinkText("Code"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
                Thread.Sleep(2000);
            }
            driver.FindElement(By.LinkText("second")).Click();
            Thread.Sleep(1000);
            test.Log(Status.Pass, "Second folder clicked");

            {
                Thread.Sleep(1000);
                var element = driver.FindElement(By.LinkText("second.txt"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
                Thread.Sleep(1000);
            }
            driver.FindElement(By.LinkText("second.txt")).Click();
            Thread.Sleep(2000);
            test.Log(Status.Pass, "Second.txt file opened");
            driver.FindElement(By.Id("LC1")).Click();
            Thread.Sleep(1000);
            driver.FindElement(By.CssSelector(".selected > span:nth-child(2)")).Click();
            Thread.Sleep(1000);
            {
                Thread.Sleep(1000);
                var element = driver.FindElement(By.CssSelector(".selected > span:nth-child(2)"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
                Thread.Sleep(1000);
            }
            driver.FindElement(By.CssSelector(".d-flex:nth-child(3) > .UnderlineNav-item > span:nth-child(2)")).Click();
            Thread.Sleep(2000);
            {
                Thread.Sleep(1000);
                var element = driver.FindElement(By.LinkText("shiva2980"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
                Thread.Sleep(2000);
            }
            driver.FindElement(By.LinkText("shiva2980")).Click();
            Thread.Sleep(1000);
            driver.FindElement(By.CssSelector(".js-feature-preview-indicator-container > .Header-link")).Click();
            Thread.Sleep(1000);
            driver.FindElement(By.CssSelector(".dropdown-signout")).Click();
            Thread.Sleep(1000);
            test.Log(Status.Pass, "Logged out successfully");
            driver.FindElement(By.CssSelector(".webgl-canvas")).Click();
            Thread.Sleep(1000);
            driver.Quit();
        }

        catch (Exception e)
        {
            test.Log(Status.Fail, e.ToString());

        }

        finally
        {
            if (driver != null)
            {
                driver.Quit();
            }
        }
    }


    //    public void SetUp1()
    //    {
    //        driver = new ChromeDriver();
    //        js = (IJavaScriptExecutor)driver;
    //        vars = new Dictionary<string, object>();
    //    }
    //    [TearDown]
    //    protected void TearDown1()
    //    {
    //        driver.Quit();
    //    }
    //    [Test, Order(1)]
    //    public void ddd()
    //    {
    //        ExtentTest test = null;

    //        try
    //        {

    //            //test = extent.CreateTest("ddd");
    //            //test.Log(Status.Pass, "Chrome Browser Launched");
    //            //driver.Navigate().GoToUrl("https://www.facebook.com/");
    //            // test.Log(Status.Pass, "Facebook URL Entered");
    //            // driver.Manage().Window.Maximize();
    //            //Thread.Sleep(500);
    //            //driver.FindElement(By.Id("email")).SendKeys("rockzshiva@gmail.com");
    //            //Thread.Sleep(2000);
    //            //test.Log(Status.Pass, "Username Entered");
    //            //Thread.Sleep(3000);
    //            //driver.Quit();
    //        }

    //        catch (Exception e)
    //        {
    //            test.Log(Status.Fail, e.Message);
    //        }
    //        finally
    //        {
    //            if (driver != null)
    //            {
    //                driver.Quit();
    //            }
    //        }
    //    }

    public void SetUp1()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown1()
    {
        driver.Quit();
    }
    [Test, Order(1)]
    public void GoogleNewsSearch()
    {
        ExtentTest test = null;

        try
        {

            test = extent.CreateTest("GoogleNewsSearch");
            test.Log(Status.Pass, "Chrome Browser Launched");
            driver.Navigate().GoToUrl("https://news.google.com/");
            Thread.Sleep(1000);
            test.Log(Status.Pass, "GoogleNews URL Entered");
            driver.Manage().Window.Maximize();
            Thread.Sleep(1000);
            driver.FindElement(By.CssSelector("div:nth-child(5) > div:nth-child(4) .ICsaqd")).Click();
            Thread.Sleep(3000);
            test.Log(Status.Pass, "Clicked on India News Page");
            Thread.Sleep(6000);
            driver.Quit();
        }

        catch (Exception e)
        {
            test.Log(Status.Fail,e.Message);
        }
        finally
        {
            if (driver != null)
            {
                driver.Quit();
            }
        }
    }

    
}



